# Generated by Django 5.0.6 on 2024-05-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answer_type',
        ),
    ]
