# Generated by Django 5.0.6 on 2024-05-29 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
