# Generated by Django 5.0.6 on 2024-05-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
